version: '2.3'
services:

  api-gateway:
    build:
      context: ./services/api-gateway
      target: dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URL=mongodb://mongo:27017/dev
    volumes:
      - ./services/api-gateway/config:/app/config
      - ./services/api-gateway/src:/app/src

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  default:
    external:
      name: func_functions
